#!/bin/bash
#
# Turn the Caps Lock light on/off
#

if [ "`whoami`" != "root" ]; then
	# re-run through sudo
	exec sudo $0 $1
fi

if [ -z "$1" ]; then
	echo "usage: $0 <on|off>"
	exit 1
fi

if [ "$1" = "on" ]; then
	setleds -D +caps </dev/tty7
fi

if [ "$1" = "off" ]; then
	setleds -D -caps </dev/tty7
fi

exit 0
