#!/bin/bash
# 
# Set the active power management governor for the CPU.
#
# Note: The 'ondemand' and 'conservative' governors are only
#       valid for acpi-cpufreq, not for intel-pstate.

if [ -z "$1" ]; then
	echo "usage: $0 <mode>"
	echo "Mode can be: conservative, ondemand, powersave, performance"
	exit 1
fi

case "$1" in
	conservative|ondemand)
		sudo cpupower frequency-set -g $1
		notify-send "CPU governor set to $1"
		;;
	performance|powersave)
		sudo cpupower frequency-set -g $1
		notify-send "CPU governor set to $1"
		;;
	*)
		echo "Invalid governor: $1"
		exit 1
esac

exit 0
