#!/bin/bash

usage() {
	echo "usage: $0 <on|off|toggle>"
	exit 1
}

on() {
	killall syndaemon &>/dev/null
	synclient TouchpadOff=0
	syndaemon -i 1.5 -d -t -K
	notify-send "Touchpad enabled"
}

off() {
	killall syndaemon &>/dev/null
	synclient TouchpadOff=1
	notify-send "Touchpad disabled"
}

toggle() {
	[ "`synclient -l | grep TouchpadOff | awk '{print $3}'`" == "1" ] && on || off
}

case "$1" in
	on)     on ;;
	off)    off ;;
	toggle) toggle ;;
	*)   usage
esac
