#theme = "ayu_dark"
theme = "tokyonight"

# Vim comforts.
#   h/t to https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
#   h/t to https://rushter.com/blog/helix-editor/
[keys.normal]
0 = "goto_first_nonwhitespace"
"$" = "goto_line_end"
G = "goto_file_end"
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
"z" = { "." = "align_view_center" }
V = ["select_mode", "extend_to_line_bounds"]
C-h = "jump_view_left"
C-l = "jump_view_right"
C-k = "jump_view_up"
C-j = "jump_view_down"
H = "goto_previous_buffer"
L = "goto_next_buffer"
# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]
C-r = ":reflow"
# Show line count for current file.
C-g = ":echo %sh{wc -l <%{buffer_name}} lines"

[keys.select]
0 = "goto_first_nonwhitespace"
"$" = "goto_line_end"
"\\" = { 0 = "goto_line_start" }
G = "extend_to_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

[keys.normal."\\"]
0 = "goto_line_start"
f = ":format"
w = ":toggle soft-wrap.enable"
o = ":buffer-close-others"

[keys.insert]
# Useful on keyboards with missing/broken Esc.
#k = { j = "normal_mode" }

[editor]
cursorline = true
bufferline = "multiple"
color-modes = true
true-color = true
trim-trailing-whitespace = true
trim-final-newlines = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.file-picker]
hidden = true
git-ignore = false
